import Link from 'next/link';
import {getCmsPage,getLeadership} from '@/lib/cms';
import {CmsImage} from '@/components/CmsImage';
export const revalidate=60;
export const metadata={title:'Company'};
export default async function Page(){const [page,leaders]=await Promise.all([getCmsPage('company'),getLeadership()]);return <main>
<section className="company-hero"><div className="company-hero__image" style={page?.hero_image_url?{backgroundImage:`url(${page.hero_image_url})`}:undefined}/><div className="company-hero__overlay"/><div className="container company-hero__content"><p className="kicker kicker--light">{page?.eyebrow||'About Plekxa'}</p><h1>{page?.headline||'We are an entertainment and media company.'}</h1><p>{page?.summary||'We create stories, music, experiences and platforms that help people get more out of life.'}</p></div></section>
<section className="statement-section"><div className="container statement-grid"><p className="kicker">Our purpose</p><div><h2>{page?.title||'Helping people live their best lives.'}</h2>{page?.body?<>{page.body.split(/\n{2,}/).map((x,i)=><p key={i}>{x}</p>)}</>:<><p>That purpose is broad because life is broad. Entertainment can make an ordinary evening unforgettable, help someone through a difficult season, bring friends together or open a door into a completely different world.</p><p>Plekxa exists to create more of those moments—and to build the company, talent, media and platforms needed to deliver them at scale.</p></>}</div></div></section>
{leaders.length>0&&<section className="news-home"><div className="container section-heading-row"><div><p className="kicker">Leadership</p><h2>The people building Plekxa.</h2></div></div><div className="container editorial-grid">{leaders.map((leader,index)=><article className={`editorial-card editorial-card--${['one','two','three'][index%3]}`} key={leader.id}><CmsImage src={leader.image_url} alt={leader.name} className="editorial-card__art"/><div><p>{leader.role}</p><h3>{leader.name}</h3><span>{leader.bio}</span></div></article>)}</div></section>}
<section className="statement-section"><div className="container statement-grid"><p className="kicker">Where we are going</p><div><h2>From a creator platform to a global entertainment ecosystem.</h2><p>Plekxa Studio is our first major platform. Over time, the wider Plekxa ecosystem will connect creation with audiences through media, consumer products and real-world experiences.</p><Link href="/products" className="arrow-link">Explore the ecosystem <span>↗</span></Link></div></div></section>
</main>}
